# Minimal steps:
#   docker-compose down
#   docker-compose up --build
#   docker-compose run web rails db:setup
#   curl -sH "Authorization: Bearer TOKEN" localhost:3000/api/v1/keys

version: "3.8"
services:
  db:
    image: postgres
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      cache_from:
        - ghcr.io/joshpencheon/pseudonymisation_service:latest
    image: ghcr.io/joshpencheon/pseudonymisation_service:latest
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: enabled
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
