name: Docker Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare containers
      run: docker-compose up --build -d
    - name: Prepare DB
      run: docker-compose run -e RAILS_ENV=test web rails db:create
    - name: Run tests
      run: docker-compose run web rails test

  push:
    runs-on: ubuntu-latest

    needs: build_and_test

    if: github.ref == 'refs/heads/master'

    env:
      IMAGE: ghcr.io/joshpencheon/pseudonynmisation_service

    steps:
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --tag $IMAGE:$GITHUB_SHA --cache-from $IMAGE:latest
    - name: Push image
      run: docker push $IMAGE:$GITHUB_SHA

