name: Docker Build

on:
  push:
  pull_request:
    branches: [ master ]

env:
  IMAGE: ghcr.io/joshpencheon/pseudonymisation_service
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - uses: actions/checkout@v2
    - name: Build commit image
      run: docker build . --tag $IMAGE:$GITHUB_SHA --cache-from $IMAGE:latest
    - name: Push commit image
      run: docker push $IMAGE:$GITHUB_SHA

  test:
    runs-on: ubuntu-latest

    needs: build

    env:
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - uses: actions/checkout@v2
    - name: Pull commit image
      run: docker pull $IMAGE:$GITHUB_SHA
    - name: Prepare containers
      run: docker-compose build --build-arg BUILDKIT_INLINE_CACHE=1
    - name: Start containers in the background
      run: docker-compose up -d
    - name: Prepare DB
      run: docker-compose run -e RAILS_ENV=test web rails db:create
    - name: Run tests
      run: docker-compose run web rails test

  push:
    runs-on: ubuntu-latest

    needs:
    - build
    - test

    if: github.ref == 'refs/heads/master'

    steps:
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Pull commit image
      run: docker pull $IMAGE:$GITHUB_SHA
    - name: Tag latest image
      run: docker tag $IMAGE:$GITHUB_SHA $IMAGE:latest
    - name: Push latest image
      run: docker push $IMAGE:latest

