name: Docker Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - uses: actions/checkout@v2
    - name: Prepare containers
      run: docker-compose up -d --build --build-arg BUILDKIT_INLINE_CACHE=1
    - name: Prepare DB
      run: docker-compose run -e RAILS_ENV=test web rails db:create
    - name: Run tests
      run: docker-compose run web rails test

  push:
    runs-on: ubuntu-latest

    needs: build_and_test

    if: github.ref == 'refs/heads/master'

    env:
      IMAGE: ghcr.io/joshpencheon/pseudonymisation_service
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build . --tag $IMAGE:latest --tag $IMAGE:$GITHUB_SHA --cache-from $IMAGE:latest
    - name: Push image
      run: docker push --all-tags $IMAGE

